jwt:
  secret: secret

spring:
  redis:
    host: localhost
    port: 6379
    password:

  datasource:
    url: jdbc:mysql://localhost:3306/codigo_booking
    username: root
    password: letmein
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true